### PR TITLE
Countdown Timer and Health Bar

### PR DESCRIPTION
**Pull request by jideadedipe**
- The timer was set to 3 mins and counts down
-Time left is also represented using a timer bar

### CODE REVIEW

**Review by Delphinium028 — APPROVED** [review]

**Comment by Jensen5796** [comment]
There are merge conflicts with the Main scene file, and I can't tell which ones to keep. Last time I made decisions on this, I broke the main branch - it isn't clear in the YAML file what you're keeping and what you're losing. 

We have 2 options:
1) is to make a new branch off of main, and cherry-pick the commits from this branch on to that branch. It will still create a merge conflict, but trying to deal with the conflict on that branch won't break the main branch. If it fails, then we delete that temporary branch and try again.
2) is to make a new branch off of main, and apply the same changes within unity that were done to create this branch. This option might take longer, but we'd know for sure we didn't lose anything when sorting out the merge conflict. Jide would be the best person to do this because he knows what he did to make countdown and healthbar.

What do you think? @jideadedipe @Delphinium028 @TD1009

**Comment by Delphinium028** [comment]
> There are merge conflicts with the Main scene file, and I can't tell which ones to keep. Last time I made decisions on this, I broke the main branch - it isn't clear in the YAML file what you're keeping and what you're losing.
> 
> We have 2 options:
> 
> 1. is to make a new branch off of main, and cherry-pick the commits from this branch on to that branch. It will still create a merge conflict, but trying to deal with the conflict on that branch won't break the main branch. If it fails, then we delete that temporary branch and try again.
> 2. is to make a new branch off of main, and apply the same changes within unity that were done to create this branch. This option might take longer, but we'd know for sure we didn't lose anything when sorting out the merge conflict. Jide would be the best person to do this because he knows what he did to make countdown and healthbar.
> 
> What do you think? @jideadedipe @Delphinium028 @TD1009

I think making a new branch off of main is a better way so we don't have to deal with so much conflicts, but still depend on Jide

**Comment by jideadedipe** [comment]
> There are merge conflicts with the Main scene file, and I can't tell which ones to keep. Last time I made decisions on this, I broke the main branch - it isn't clear in the YAML file what you're keeping and what you're losing.
> 
> We have 2 options:
> 
> 1. is to make a new branch off of main, and cherry-pick the commits from this branch on to that branch. It will still create a merge conflict, but trying to deal with the conflict on that branch won't break the main branch. If it fails, then we delete that temporary branch and try again.
> 2. is to make a new branch off of main, and apply the same changes within unity that were done to create this branch. This option might take longer, but we'd know for sure we didn't lose anything when sorting out the merge conflict. Jide would be the best person to do this because he knows what he did to make countdown and healthbar.
> 
> What do you think? @jideadedipe @Delphinium028 @TD1009

Yeah!! we have to guide Main branch for a lot has been put to it, therefore lets go by the first option by making new branch off the main and pick commits from this branch to the one we are make.

**Comment by TD1009** [comment]
Do you need me to do any action? I think @jideadedipe can work with the first option to see what conflict in his code with the current main.

**Pull request closed without merging**
